CREATE TABLE `trips` ( 
    `id` INT( 11 ) NOT NULL, 
    `tc_id` INT( 11 ) NULL, 
    `trip_id` VARCHAR( 45 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `main_leg` INT( 1 ) NULL, 
    `trip_link` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `driver_id` INT( 11 ) NULL, 
    `trip_created_at` DATETIME NULL, 
    `trip_departure_datetime` DATETIME NULL,
    `departure_address` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
    `destination_address` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `departure_city` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `destination_city` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `departure_state` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `destination_state` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `departure_country` VARCHAR( 45 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `destination_country` VARCHAR( 45 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `country` VARCHAR( 45 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `seats_offered` INT( 1 ) NULL, 
    `trip_distance` INT( 5 ) NULL, 
    `suggested_price` INT( 6 ) NULL, 
    `price` INT( 6 ) NULL, 
    `trip_canceled` INT( 1 ) NULL, 
    `auto_accept` INT( 1 ) NULL, 
    `trip_comment` INT( 1 ) NULL, 
    `driver_message` INT( 1 ) NULL, 
    `pax_message` INT( 1 ) NULL, 
    `recurrent` INT( 1 ) NULL, 
    `ladies_only` INT( 1 ) NULL, 
    `is_return` INT( 1 ) NULL, 
    `seats_booked` INT( 1 ) NULL, 
    `seats_approved` INT( 1 ) NULL, 
    `seats_canceled` INT( 1 ) NULL, 
    `seats_rejected` INT( 1 ) NULL, 
    `promo_code` VARCHAR( 45 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL, 
    `description_code` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
     PRIMARY KEY ( `id` )
 )
CHARACTER SET = utf8
COLLATE = utf8_general_ci
ENGINE = INNODB;