CREATE TABLE `users` ( 
	`id` INT( 11 ) UNSIGNED NOT NULL, 
	`guid` char(36) NOT NULL UNIQUE,  
	`first_name` VARCHAR( 200 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`last_name` VARCHAR( 200 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`birthdate` DATE NULL,
	`age` INT( 3 ) NULL, 
	`gender` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`created_at` DATETIME NULL, 
	`country` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
	`locale` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
	`affiliate` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`phone_number` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`email` VARCHAR( 200 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`facebook_profile` VARCHAR( 45 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`pref_chat` INT( 1 ) UNSIGNED NULL, 
	`pref_music` INT( 1 ) UNSIGNED NULL, 
	`pref_smoking` INT( 1 ) UNSIGNED NULL, 
	`pref_pets` INT( 1 ) UNSIGNED NULL, 
	`pref_food` INT( 1 ) UNSIGNED NULL, 
	`share_phone` INT( 1 ) UNSIGNED NULL, 
	`share_email` INT( 1 ) UNSIGNED NULL, 
	`share_facebook` INT( 1 ) UNSIGNED NULL, 
	`share_nothing` INT( 1 ) NULL, 
	`facebook_friends` INT( 5 ) UNSIGNED NULL, 
	`phone_verified` INT( 1 ) UNSIGNED NULL, 
	`email_verified` INT( 1 ) UNSIGNED NULL, 
	`badges` VARCHAR( 200 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL, 
	`ratings` INT( 5 ) UNSIGNED NULL, 
	`total_rating` INT( 5 ) UNSIGNED NULL, 
	`have_comments` INT( 1 ) UNSIGNED NULL, 
	`android` INT( 1 ) UNSIGNED NULL, 
	`ios` INT( 1 ) UNSIGNED NULL, 
	`first_offer` DATE NULL,
	`last_offer` DATE NULL, 
	`first_driver_with_booking` DATE NULL,
	`last_driver_with_booking` DATE NULL,
	`first_driver` DATE NULL, 
	`last_driver` DATE NULL, 
	`total_offer` INT( 6 ) UNSIGNED NULL, 
	`first_booking` DATE NULL, 
	`last_booking` DATE NULL, 
	`first_pax` DATE NULL, 
	`last_pax` DATE NULL, 
	`total_booking` INT( 6 ) UNSIGNED NULL,
	 PRIMARY KEY ( `id` )
 )
CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT '		'
ENGINE = INNODB;
CREATE INDEX `_gender` USING BTREE ON `users`( `gender` )
