CREATE TABLE trips ( 
    id integer NOT NULL PRIMARY KEY, 
    tc_id integer NULL, 
    trip_id VARCHAR( 45 ) NULL, 
    main_leg integer NULL, 
    trip_link VARCHAR( 200 ) NULL, 
    driver_id integer NULL, 
    trip_created_at timestamp NULL, 
    trip_departure_datetime timestamp NULL, 
    departure_address VARCHAR( 45 ) NULL, 
    destination_address VARCHAR( 45 ) NULL, 
    departure_city VARCHAR( 45 ) NULL, 
    destination_city VARCHAR( 45 ) NULL, 
    departure_state VARCHAR( 45 ) NULL, 
    destination_state VARCHAR( 45 ) NULL, 
    departure_country VARCHAR( 45 ) NULL, 
    destination_country VARCHAR( 45 ) NULL, 
    country VARCHAR( 45 ) NULL, 
    seats_offered integer NULL, 
    trip_distance integer NULL, 
    suggested_price integer NULL, 
    price integer NULL, 
    trip_canceled integer NULL, 
    auto_accept integer NULL, 
    trip_comment integer NULL, 
    driver_message integer NULL, 
    pax_message integer NULL, 
    recurrent integer NULL, 
    ladies_only integer NULL, 
    is_return integer NULL, 
    seats_booked integer NULL, 
    seats_approved integer NULL, 
    seats_canceled integer NULL, 
    seats_rejected integer NULL, 
    promo_code VARCHAR( 45 ) NULL, 
    description_code VARCHAR( 200 ) NULL);